### ISSUE TITLE
Greedy Localized Data Augmentation

### ISSUE THREAD

**Issue by Booooooooooo** [PS06/DIDH#2]
Thanks for your work! I am very curious about greedy localized data augmentation, but I can't find [COPY-BLEND Augmentation for Low Level Vision Tasks] in arxiv and google. Also your link to GLDA returns 404 not found. 
So how can I get to the implementation details of Greedy localized data augmentation? Thx.

**Comment by PS06** [comment]
Hi, Thanks for reaching out. The COPY-BLEND paper and code should be available on arxiv and github by the end of next week.
That should help your case.

**Comment by Booooooooooo** [comment]
Thank you very much! I will keep an eye on it.
